BlockGenerator :
  block_shape  : [96, 96, 96]
  out_shape    : [48, 48, 48]
  crop_shape   : [256, 256, -1]
  stride       : 48
  # crop_shape   : [256, 256, 70]
  n_workers    : 1
  ordered      : True
  verbose      : False

Augmentor      :
  window_width : 100
  window_level : 50
  n_workers    : 1
  verbose      : False

BatchGenerator :
  batch_size   : 32
  n_workers    : 1
  verbose      : False
